name: ddundddun
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  image_picker: ^1.0.7
  path_provider: ^2.1.2
  sqflite: ^2.3.3
  image_gallery_saver: ^2.0.3
  dio: ^5.4.2+1
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  intl: ^0.19.0
  permission_handler: ^11.3.1
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  cloudinary_public: ^0.23.1
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo2.png